name: Pull request - Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test-monorepo-labelling:
    runs-on: ubuntu-latest
    name: Test monorepo labelling
    steps:
      - uses: ledongthuc/monorepolabeling@main
        id: labelchanges
        with:
          matching-patterns: |-
            /file/a/*:serviceA
            /file/b/*:serviceB
      - name: Print labels
        run: echo "Service changes ${{ steps.hello.labelchanges.labels }}"
